### ISSUE TITLE
[BUG] Selecting admin account for jellyseerr then changing to local account wont use the local account

### ISSUE THREAD

**Issue by lukeeexd** [giuseppe99barchetta/SuggestArr#100]
**Describe the bug**
 intially used the admin account for Jellyseerr. I then edited the configuration and used a local account. When requests were made to jellyseerr, they used the admin account
**To Reproduce**
1. Brand new install
2. Use admin account for jellyseerr
3. After configuration is complete, use local account for Jellyseerr
4. Run the cron and the requests will come from the admin account.

**Expected behavior**
The requests to come from the local account

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Synology using docker
 - Browser: Edge
 - Version: 131.0.2903.99

**Additional context**

**Comment by lukeeexd** [comment]
After further investigation, it seems it's failing to login as my local user. 2024-12-14 21:51:52,726 - SeerClient - ERROR - Login failed: 500

**Comment by giuseppe99barchetta** [comment]
> After further investigation, it seems it's failing to login as my local user. 2024-12-14 21:51:52,726 - SeerClient - ERROR - Login failed: 500
> 
> 
> 
> Edit: Okay it's because I had the local signi-n in option disabled in Jellyseerr :D

Thank you for the report! So can you confirm that I can close this issue?
