### ISSUE TITLE
[REQ] Don't request Movies or Shows already in Jellyfin library.

### ISSUE THREAD

**Issue by lukeeexd** [giuseppe99barchetta/SuggestArr#101]
**Is your feature request related to a problem? Please describe.**
If media is available in jellyfin, it will still be requested in Jellyseerr.

**Describe the solution you'd like**
Don't request stuff already available in Jellyfin, it just clogs up recent reequests.

**Describe alternatives you've considered**

**Additional context**

**Comment by giuseppe99barchetta** [comment]
Feature already implemented. Could you double-check your configuration? When the Docker volume is mounted correctly, two files should be created: one for the configuration and one for the database.

**Comment by lukeeexd** [comment]
> Feature already implemented. Could you double-check your configuration? When the Docker volume is mounted correctly, two files should be created: one for the configuration and one for the database.

Yes I have config.yml and requests.db

**Comment by giuseppe99barchetta** [comment]
In the first run it should add all your jellyfin content to the request.db, could you please open it and check if your library content is here?

**Comment by lukeeexd** [comment]
> In the first run it should add all your jellyfin content to the request.db, could you please open it and check if your library content is here?

It doesnt seem like it. I'm using sql browser and I can't see anything that resembles my media in it

**Comment by lukeeexd** [comment]
@giuseppe99barchetta any idea?
