### ISSUE TITLE
Make an image for dockerhub

### ISSUE THREAD

**Issue by Druidblack** [giuseppe99barchetta/SuggestArr#12]
Good afternoon. Is it possible in the future to create an image for dockerhub so that users can receive a ready-made image without creating it in detail? So that you can then receive updates by replacing the image.

**Comment by giuseppe99barchetta** [comment]
Hi! Thank you for your suggestion.

The good news is that the Docker image for the project is already available on Docker Hub! You can pull it directly without needing to build it yourself.

To get the latest version of the image, you can run the following command:

`docker pull ciuse99/suggestarr:latest`

After that, you can create and run the container using Docker Compose or `docker run`.

Let me know if you have any questions!

**Comment by giuseppe99barchetta** [comment]
Hi @Druidblack,

Could you clarify your request a bit more? I’d like to better understand your needs so I can address this properly. 

Looking forward to your clarification so I can explore this further and close the issue.
