### ISSUE TITLE
Add support for Overseerr.

### ISSUE THREAD

**Issue by Toastypaws** [giuseppe99barchetta/SuggestArr#15]
Hello !
Would you ever add support for Overseerr as well?

Cheers,

**Comment by giuseppe99barchetta** [comment]
Hi,

I'm currently working on adding support for Plex, and I'm excited to share that support for Overseer will also be included in the upcoming updates. I appreciate your patience and interest in these features. Stay tuned for further announcements and feel free to reach out if you have any more suggestions or questions!
