### ISSUE TITLE
Jelly

### ISSUE THREAD

**Issue by drorengel** [giuseppe99barchetta/SuggestArr#17]
I created new local user with admin role. I picked the user from the drop down and forced the run. I see the following error 

SuggestArr  | 2024-10-18 16:33:22,013 - JellyfinClient - ERROR - Failed to retrieve users: 404
SuggestArr  | 2024-10-18 16:33:22,127 - JellyseerClient - INFO - Fetched 25 total requests from Jellyseer.

how I can debug this issue? no other info so I assume the job is not running

**Comment by giuseppe99barchetta** [comment]
Could you please double check the API Key and the URL of Jellyfin? The URL should be like` http://localhost:8096`

**Comment by drorengel** [comment]
ok, the issue was the address should not include the / at the end of the URL

http://localhost:8096 - correct
http://localhost:8096/ - error.
