### ISSUE TITLE
[REQ] Fetch all library content before request

### ISSUE THREAD

**Issue by Druidblack** [giuseppe99barchetta/SuggestArr#18]
I have a suggestion. When I tried your program now, I saw that it made a lot of requests to jellyseerr for movies that I already have on radarr (they were not added through jellyseerr). Maybe the program could run ai radar and sonar and not make unnecessary requests to jellyseerr?

**Comment by giuseppe99barchetta** [comment]
I understand the concern about making unnecessary requests to Jellyseerr for content that’s already in Radarr or Sonarr but wasn’t added through Jellyseerr. While it’s possible to implement such a feature, it would likely become quite complex and would significantly increase the number of API calls and checks required for each suggested content.

However, I can look into adding a feature that would check for content already present in your library that isn’t tracked by Jellyseerr. This might be a simpler and more efficient way to avoid redundant requests.

Let me know your thoughts!
