### ISSUE TITLE
Login failed: 403. No session cookie found.

### ISSUE THREAD

**Issue by Joly0** [giuseppe99barchetta/SuggestArr#20]
I normally use login through jellyfin, but i created a separate local user for SuggestArr in Jellyseer. But whenever suggestarr tries to use that account, i just get the error message:
```
2024-10-19 02:16:08,142 - JellyseerClient - ERROR - Login failed: 403. No session cookie found.
2024-10-19 02:16:08,142 - JellyseerClient - ERROR - Error response: {'message': 'Access denied.'}
```
I tried logging into that account in jellyseer and that works without any issues.
Also another problem that is shown here, is that if suggestarr cant login using the provided account, it will just use the api account, which in my case is the admin with auto-approve permissions. So suggestarr just adds a bunch of movies (some which i already have and some that i dont want) automatically to radarr/sonarr without me having the option to disable this behaviour so i have to approve the requests first.
Imo, if a jellyseer is selected to be used and login doesnt work, suggestarr shouldnt use the admin account.

Edit:
Also button to enable/disable suggestarr in the webui would be cool aswell as a dry-run option

**Comment by giuseppe99barchetta** [comment]
I’ll definitely look into this later, but yes, it’s crucial to block SuggestArr from using the admin account if it can’t log in with the selected user. I’ll make sure to implement that change. Additionally, I’ll work on adding a button in the web UI to enable or disable SuggestArr.

By the way, have you double-checked that the password you entered for the Jellyseer user in SuggestArr is correct? Just to rule out any possible issue with the credentials.

**Comment by Joly0** [comment]
Yes, i made sure the password is correct. Though i am not sure what suggestarr uses to login. I can only select the user, but it looks like login through the username doesnt work for local users, only using mail address

**Comment by giuseppe99barchetta** [comment]
> Yes, i made sure the password is correct. Though i am not sure what suggestarr uses to login. I can only select the user, but it looks like login through the username doesnt work for local users, only using mail address

Hi! Currently, only local accounts without an associated email are supported. This means that your local account only requires a username to log in. I'm working on a fix to improve this process. Thanks for your patience!
