### ISSUE TITLE
[BUG] Can't connect Jellyfin on startup with API

### ISSUE THREAD

**Issue by cup1dstunt** [giuseppe99barchetta/SuggestArr#27]
**Describe the bug**
I tried running suggestarr as a docker. During the first startup, I was asked to enter API keys. It worked flawlessly for TMDB, but I am stuck. It does not accept my API key for some reason. I run jellyfin on the same server behind a reverse proxy and entered the public URL and entered a valid API key. However, I can't advance. It says: "Failed to validate Jellyfin Key or retrieve libraries."
Is there a specific jellyfin configuration that is necessary (jellyfin works on my system with other API for jellyseer, jellystat, tracktv, homepage etc) or is this a bug?

**To Reproduce**
see above

**Expected behavior**
suggestarr accepting my API key.

**Screenshots**

**Desktop (please complete the following information):**
Unraid, docker

**Comment by giuseppe99barchetta** [comment]
Hi! I’m sorry for the issue you’ve encountered. It seems the link you’re using might include an unnecessary trailing slash. Please try using the link like this:

`http://127.0.0.1:8096`

Let me know if this resolves the problem. A permanent fix will be released in the coming days.

This version is clearer and more concise.

**Comment by cup1dstunt** [comment]
Thank you for the quick answer. Unfortunately it did not solve the problem. It can handle external URLs right? I don't have to point it to a local ip (I also tried that but to no avail)?

I will keep an eye open for the upcoming fix, I am really eager to try suggestArr out, I think it has great potential because it's honestly a missing piece.

**Comment by giuseppe99barchetta** [comment]
> Thank you for the quick answer. Unfortunately it did not solve the problem. It can handle external URLs right? I don't have to point it to a local ip (I also tried that but to no avail)?
> 
> I will keep an eye open for the upcoming fix, I am really eager to try suggestArr out, I think it has great potential because it's honestly a missing piece.

Hi! Should be fixed in the `latest` tag!

**Comment by cup1dstunt** [comment]
Thank you very much! I am enjoying suggestarr so far :)
