### ISSUE TITLE
[BUG] Settings will not save after going through setup wizard

### ISSUE THREAD

**Issue by Rupie17** [giuseppe99barchetta/SuggestArr#31]
**Describe the bug**
Deployed the docker container through unraid.  Filled in environment variables and successfully started up.
Navigating to web ui and walking through set up wizard I can go through steps 1-5, but when I go to click save on step 5 nothing happens.

Checking the logs I see these errors:

**2024-10-24 09:48:21,059 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.**
2024-10-24 09:48:21,061 INFO supervisord started with pid 1
2024-10-24 09:48:22,063 INFO spawned: 'cron' with pid 7
2024-10-24 09:48:22,065 INFO spawned: 'uvicorn' with pid 8
2024-10-24 09:48:22,902 - utils.utils - INFO - 
        
        =====================================================================================
        |   Welcome to the SuggestArr Application!                                          |
        |   Manage your settings through the web interface at: http://localhost:5000        |
        |   Fill in the input fields with your data and let the cron job handle the rest!   |
        |   To run the automation process immediately, click the 'Force Run' button.        |
        |   The 'Force Run' button will appear only after you save your settings.           |
        |   To leave feedback visit: https://github.com/giuseppe99barchetta/SuggestArr      |
        =====================================================================================
        
2024-10-24 09:48:23,902 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-10-24 09:48:23,903 INFO success: uvicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
**2024-10-24 09:49:42,597 - config.config - WARNING - /app/config/config_files/config.yaml not found. Creating a new one with default values.**
2024-10-24 09:49:42,597 - blueprints.config.routes - ERROR - Error loading configuration: Object of type function is not JSON serializable

(This happens when I click save on step 5)
**2024-10-24 09:50:59,267 - blueprints.config.routes - ERROR - Error saving configuration: [Errno 2] No such file or directory: '/app/config/config_files/config.yaml'**

In the unraid template, I have mapped a volume to the config_files folder but that does not get created on startup and no config.yaml file is automatically created as suggested in the logs.

**To Reproduce**
1. Log in to Unraid mgmt console, goto apps and search for suggestarr
2. Click on suggestarr
3. Fill in config details for the template and deploy
4. Navigate to web ui at http://localhost:5155
5. Walk through set up
6. Click save on step 5 and see error in logs.

**Expected behavior**
I'd expect the save button to commit the settings to the config.yaml file located at /app/config/config_files in the container.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 131.0.3

**Comment by giuseppe99barchetta** [comment]
Hi! 

Unfortunately in UnRaid the docker-compose is not up-to-date, you need to configure it like this:


services:
  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: SuggestArr
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./config_files:/app/config/config_files

**Comment by Rupie17** [comment]
Thanks very much for the speedy reply.  I figured that might be the case but thanks for confirming!

**Comment by giuseppe99barchetta** [comment]
> Thanks very much for the speedy reply.  I figured that might be the case but thanks for confirming!

If you know how to update the Docker Compose in the Unraid app store, that would be very helpful.

Unfortunately, I haven’t published SuggestArr myself in UnRaid, so I’m not familiar with it.

**Comment by pairofcrocs** [comment]
I have a PR on it now.

In the mean time, remove all the EVs execpt the webui, and add one for /config.

Container Path: /app/config/config_files
Host Path: /mnt/user/appdata/suggestarr
