### ISSUE TITLE
New Install unable to sort 90% of content and no requests are made either

### ISSUE THREAD

**Issue by angelgtc87** [giuseppe99barchetta/SuggestArr#32]
I just setup Plex and Overseerr and although everything is configured it won't match anything in the library, I get many of below

```
ContentAutomation - WARNING - Error while processing item: Missing key for movie 'Deadpool 2' << pretty common movie as an example
```

and then followed by 3000 + messages for 

```
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,785 - ContentAutomation - WARNING - Error while processing item: 
2024-10-24 14:14:24,810 - ContentAutomation - INFO - Total media requested: 0
```

my config

```yml
CRON_TIMES: 0 0 * * *
JELLYFIN_API_URL: ''
JELLYFIN_LIBRARIES: []
JELLYFIN_TOKEN: ''
MAX_CONTENT_CHECKS: 10
MAX_SIMILAR_MOVIE: 5
MAX_SIMILAR_TV: 2
PLEX_API_URL: http://10.0.15.5:32400
PLEX_LIBRARIES:
- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PLEX_TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SEER_API_URL: https://publicurl.com
SEER_TOKEN:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SEER_USER_NAME: 'localaccount'
SEER_USER_PSW: ' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
SELECTED_SERVICE: plex
TMDB_API_KEY:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by giuseppe99barchetta** [comment]
Can I ask you which provider for metadata are you using for the libraries?

**Comment by angelgtc87** [comment]
in plex ? I believe it's whatever plex suggests 

<img width="392" alt="Screenshot 2024-10-24 at 3 03 44 PM" src="https://github.com/user-attachments/assets/74c1258d-9e70-48c4-98f5-899728e6ceef">
<img width="419" alt="Screenshot 2024-10-24 at 3 03 55 PM" src="https://github.com/user-attachments/assets/4b50cc12-64e2-4f4d-9424-ceb9d8e019c4">

**Comment by giuseppe99barchetta** [comment]
> in plex ? I believe it's whatever plex suggests 
> 
> 
> 
> <img width="392" alt="Screenshot 2024-10-24 at 3 03 44 PM" src="https://github.com/user-attachments/assets/74c1258d-9e70-48c4-98f5-899728e6ceef">
> 
> <img width="419" alt="Screenshot 2024-10-24 at 3 03 55 PM" src="https://github.com/user-attachments/assets/4b50cc12-64e2-4f4d-9424-ceb9d8e019c4">
> 
> 

Probably that's the problem, but I'm not sure, would you try changing the agent to TMDB and let me know if it fixes your problem?

**Comment by angelgtc87** [comment]
I have a test plex server with 1 library , I can try on that, if that works I might have to wait to deploy the app since the plex scanners are really fast :/

**Comment by angelgtc87** [comment]
I redid the config, added my test server with 1 anime library set to tmdb and rescanned, looks like it works, but it can't request from overseerr

```
2024-10-24 15:19:03,609 - SeerClient - ERROR - Error during login to Seer.
2024-10-24 15:19:03,609 - ContentAutomation - INFO - Requested tv: Gods' Games We Play
2024-10-24 15:19:03,609 - ContentAutomation - INFO - Total media requested: 1
```

**Comment by giuseppe99barchetta** [comment]
> I redid the config, added my test server with 1 anime library set to tmdb and rescanned, looks like it works, but it can't request from overseerr
> 
> 
> 
> ```
> 
> 2024-10-24 15:19:03,609 - SeerClient - ERROR - Error during login to Seer.
> 
> 2024-10-24 15:19:03,609 - ContentAutomation - INFO - Requested tv: Gods' Games We Play
> 
> 2024-10-24 15:19:03,609 - ContentAutomation - INFO - Total media requested: 1
> 
> ```

Have you verified if the request goes through completely? And have you double-checked the Overseer credentials to ensure they’re correct?

**Comment by angelgtc87** [comment]
it doesn't find my overseerr local account so I left it blank to use the admin

**Comment by giuseppe99barchetta** [comment]
> it doesn't find my overseerr local account so I left it blank to use the admin
> 
> 

That’s strange, I’ve never encountered this issue before. In the Overseer settings steps, does the login button turn green after you log in?

**Comment by angelgtc87** [comment]
yes all green

**Comment by angelgtc87** [comment]
<img width="824" alt="Screenshot 2024-10-24 at 3 27 50 PM" src="https://github.com/user-attachments/assets/29598e07-737d-4bbb-91f2-f49dfddbd526">

**Comment by giuseppe99barchetta** [comment]
> <img width="824" alt="Screenshot 2024-10-24 at 3 27 50 PM" src="https://github.com/user-attachments/assets/29598e07-737d-4bbb-91f2-f49dfddbd526">
> 
> 

Yes, but you should try with a local Jellyseer user if you want to manually approve the request. Otherwise like this should be fine

**Comment by angelgtc87** [comment]
I have overseerr not jellyseerr, I'm fine autoapproving, however the request doesn't go through

**Comment by giuseppe99barchetta** [comment]
> I have overseerr not jellyseerr, I'm fine autoapproving, however the request doesn't go through

Yeah it's the same thing. Shares the same API

**Comment by angelgtc87** [comment]
yea so idk why request doesn't go through 

this is full log from RUN NOW button

```

2024-10-24 15:27:31,620 - PlexClient - INFO - Fetching libraries from Plex.
2024-10-24 15:36:42,171 - config.config - INFO - Cron job updated with: 0 0 * * *
2024-10-24 15:36:44,990 - SeerClient - INFO - Fetched 1495 total requests from Jellyseer.
2024-10-24 15:36:44,991 - ContentAutomation - INFO - Fetching recently watched content from Plex
2024-10-24 15:36:44,992 - ContentAutomation - INFO - Processing item: Moving
2024-10-24 15:36:45,043 - ContentAutomation - INFO - Skipping [tv, Spice and Wolf: MERCHANT MEETS THE WISE WOLF]: already requested.
2024-10-24 15:36:45,074 - SeerClient - ERROR - Login failed: 403. No session cookie found.
2024-10-24 15:36:45,074 - SeerClient - ERROR - Error response: {'message': 'Access denied.'}
2024-10-24 15:36:45,074 - SeerClient - ERROR - Error during login to Seer.
2024-10-24 15:36:45,074 - ContentAutomation - INFO - Requested tv: Gods' Games We Play
2024-10-24 15:36:45,074 - ContentAutomation - INFO - Total media requested: 1
```

**Comment by giuseppe99barchetta** [comment]
Yeah sometimes return an access denied error from Overseer but the request should be completed anyway

**Comment by UberMentch** [comment]
I've been getting this error all day, both on 1.0.7 and 1.0.8. Using local IP addresses for Plex and a local account on Overseerr.

**Comment by pairofcrocs** [comment]
Also can confirm. Cannot find local Overseerr either.

**Comment by giuseppe99barchetta** [comment]
Hi @twist3dimages , @UberMentch and @vednolacni.

Could you please check which network the Overseer container is on? You might try changing it to bridge or host, or alternatively, set SuggestArr to use the same network as Overseer. It’s possible that SuggestArr is unable to access Overseer's network.

**Comment by giuseppe99barchetta** [comment]
> still having issues after update, overseerr, suggestarr and plex all on same custom bridge docker network.

Could you please share the updated logs? I've made many changes in the recent updates, so if it's not too much trouble, it would be very helpful for troubleshooting. Thank you!

**Comment by UberMentch** [comment]
> Hi @twist3dimages , @UberMentch and @vednolacni.
> 
> Could you please check which network the Overseer container is on? You might try changing it to bridge or host, or alternatively, set SuggestArr to use the same network as Overseer. It’s possible that SuggestArr is unable to access Overseer's network.

I'll be able to provide more testing after work today. A quick container update this morning didn't fix the issue, but I'll try a few approaches and post results in maybe 8-10 hours

**Comment by angelgtc87** [comment]
> > still having issues after update, overseerr, suggestarr and plex all on same custom bridge docker network.
> 
> Could you please share the updated logs? I've made many changes in the recent updates, so if it's not too much trouble, it would be very helpful for troubleshooting. Thank you!

I was able to find local account ! however scan starts good for first 100 items and then it ends up in errors :/ it's like is hitting a limit 

<img width="1256" alt="Screenshot 2024-10-25 at 10 43 41 AM" src="https://github.com/user-attachments/assets/f0694bb4-786d-4fa1-aa81-c7e9e7e571c4">

**Comment by giuseppe99barchetta** [comment]
> > > still having issues after update, overseerr, suggestarr and plex all on same custom bridge docker network.
> > 
> > 
> > Could you please share the updated logs? I've made many changes in the recent updates, so if it's not too much trouble, it would be very helpful for troubleshooting. Thank you!
> 
> I was able to find local account ! however scan starts good for first 100 items and then it ends up in errors :/ it's like is hitting a limit
> 
> <img alt="Screenshot 2024-10-25 at 10 43 41 AM" width="1256" src="https://private-user-images.githubusercontent.com/28854275/380212529-f0694bb4-786d-4fa1-aa81-c7e9e7e571c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzcwNjUsIm5iZiI6MTcyOTg3Njc2NSwicGF0aCI6Ii8yODg1NDI3NS8zODAyMTI1MjktZjA2OTRiYjQtNzg2ZC00ZmExLWFhODEtYzdlOWU3ZTU3MWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE3MTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NGM3YjQ3YzQyNzU1OWY0Y2JkZWY4ZTQxNTA2MzVkYzFmM2I1YWFkMDcxZDg0MmRlMjhkMTU4ZThhYjc1ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7JJPgftEWSu40NEg3uRTyFfRlYScyCGupwKTyP7V7MQ">

I've pushed an update on `nightly `tag, can you give it a try?

**Comment by angelgtc87** [comment]
Improvements, :) ! requests are now working, however it's skipping movie library completely, it checked only tv shows, skipped anime and movies, even thought they are selected

**Comment by giuseppe99barchetta** [comment]
> Improvements, :) ! requests are now working, however it's skipping movie library completely, it checked only tv shows, skipped anime and movies, even thought they are selected

Yes, it appears that your last watched content doesn't include any anime or movies. For instance, if you've set a maximum of 10 items to check, it scans only your last 10 watched items. Currently, there seems to be a minor issue where it counts each episode as a single watched item, which could affect the results. I'll work on addressing this, but for now, it seems the issue has been resolved.

**Comment by angelgtc87** [comment]
yea thanks :) qq, this is my admin profile which I use only when I'm by myself, I have another profile that is used by the family so it will have much watched history then this, however I can't add it since it's not an admin account

**Comment by giuseppe99barchetta** [comment]
> yea thanks :) qq, this is my admin profile which I use only when I'm by myself, I have another profile that is used by the family so it will have much watched history then this, however I can't add it since it's not an admin account

Pushed another update on nighly, can you check if now fetch correctly also movie in your case? Now each episode of the same tv show count as 1 watched content

**Comment by angelgtc87** [comment]
yep it did, all good for movies. thx !
