### ISSUE TITLE
[BUG]Failed to validate Overseer Key.

### ISSUE THREAD

**Issue by aizazmueez** [giuseppe99barchetta/SuggestArr#33]
**Describe the bug**
During setup at step 4, while setting up overseer the following error is seen 
Failed to validate Overseer Key.

**To Reproduce**
1. Go to step 4 of setup.
2. Enter overseer url. In my case "http://192.168.1.200:5055"
3. Copy the overseer API from overseer settings and paste here
4. Press the check API key button.

**Expected behavior**
The key is expected and we move to step 5 of setup

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser FIREFOX
 

**Additional context**
Overseer is running in a docker container.

**Comment by giuseppe99barchetta** [comment]
How it's configured you Overseer container? Can you paste here the docker-compose?

**Comment by aizazmueez** [comment]
following is my docker-compose file for overseerr

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - NL=Europe/Amsterdam
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/mueez/overseerr/config:/app/config
    restart: unless-stopped

**Comment by giuseppe99barchetta** [comment]
Could you please try to add this in the Overseer docker-compose:

```
    networks:
      - bridge
```

Probably it's the problem, Suggestarr can't reach the network of Overseer. 

Another possible solution is to put SuggestArr in the same network as Overseer

**Comment by aizazmueez** [comment]
i updated the compose file as follows:

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - NL=Europe/Amsterdam
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/mueez/overseerr/config:/app/config
    networks:
      - bridge  
    restart: unless-stopped
    
    but i get the following error when i do docker-compose down 
    service "overseerr" refers to undefined network bridge: invalid compose project
    
    I do think the issue you mentioned is correct. I am somewhat new to this. I will see how can i put both containers on the same network.

**Comment by giuseppe99barchetta** [comment]
> i updated the compose file as follows:
> 
> services: overseerr: image: sctx/overseerr:latest container_name: overseerr environment: - LOG_LEVEL=debug - NL=Europe/Amsterdam - PORT=5055 #optional ports: - 5055:5055 volumes: - /home/mueez/overseerr/config:/app/config networks: - bridge restart: unless-stopped
> 
> ```
> but i get the following error when i do docker-compose down 
> service "overseerr" refers to undefined network bridge: invalid compose project
> 
> I do think the issue you mentioned is correct. I am somewhat new to this. I will see how can i put both containers on the same network.
> ```

You can try with the host network in both SuggestArr and Overseer

**Comment by UberMentch** [comment]
I'll be able to provide more testing after work today. A quick container update this morning didn't fix the issue, but I'll try a few approaches and post results in maybe 8-10 hours

**Comment by buhnux** [comment]
I'm having the same issue, I tried what was suggested in the updates.  

When clicking view logs I also see: 

`Error during request to https://jupiter:5055/api/v1/user?take=100: Cannot connect to host jupiter:5055 ssl:default [Name or service not known]	`

Not sure if it's trying to connect via ssl?

**Comment by giuseppe99barchetta** [comment]
> I'm having the same issue, I tried what was suggested in the updates.  
> 
> 
> 
> When clicking view logs I also see: 
> 
> 
> 
> `Error during request to http://jupiter:5055/api/v1/user?take=100: Cannot connect to host jupiter:5055 ssl:default [Name or service not known]`
> 
> 
> 
> Not sure if it's trying to connect via ssl? 

Please try to use local ip for Overseer and let me know if you get the same error

**Comment by buhnux** [comment]
yes, that works.

**Comment by giuseppe99barchetta** [comment]
> yes, that works.

Ok perfect, I need to check why SSL is broken for the requests
