### ISSUE TITLE
[BUG] Total media requested is not adhering to set value

### ISSUE THREAD

**Issue by solidsnakex37** [giuseppe99barchetta/SuggestArr#37]
**Describe the bug**
I have the "Max Similar Movies" and "Max Similar TV Shows" set to 1 each, per day, with max content fetch for each content is 10. 

However, when I hit "Run Now" to test it, it request 122 items lol 
![image](https://github.com/user-attachments/assets/afba8666-f2e1-4301-9ce0-6cfeebea546e)

![image](https://github.com/user-attachments/assets/b533f12f-d565-470c-81bc-92a7dc1a3bad)

**To Reproduce**

My setup is Emby, I selected 3 libraries (Anime, Movies, TV Shows), additional settings is as follows. 

![image](https://github.com/user-attachments/assets/09e76ce1-16a5-4842-8f34-4d03515493d0)

**Expected behavior**
I thought if I set each max similar value to "1" it would only download/request 1 similar item per library I selected 

I am running Suggestarr in Docker, in Unraid, on the latest tag/release

**Comment by giuseppe99barchetta** [comment]
Hi @solidsnakex37! Thanks for reporting the issue.

How many users do you have on your Emby server?

The “1 film and 1 TV show” refers to one content item per recently viewed film or show for the Max Content Checks setting.

For example, if you’ve recently watched 8 films and 2 TV shows, SuggestArr will request 8 films (1 for each film watched) and 2 TV shows (1 for each show watched), as long as they haven’t already been requested.

I completely understand that this can be a bit tricky to manage right now, but I’m working on implementing more granular filters to give you better control. In the meantime, the best solution to prevent too many automatic requests and downloads is to create a local Jellyseer account without auto-approval.

**Comment by solidsnakex37** [comment]
hey @giuseppe99barchetta! That makes sense, this can be boiled down to my lack of understanding on the settings lol 

I have 17 users on my Emby server currently, so does it check for suggestions across what all my users are watching? 

Thankfully I set up a local user account without auto approval so removing the 122 requests won't be a problem. When I first tried this without the Emby support I thought there was an option to choose which user on the media server you want to perform the suggestions on, unless I am misremembering. Will that be brought back?

**Comment by giuseppe99barchetta** [comment]
> hey @giuseppe99barchetta! That makes sense, this can be boiled down to my lack of understanding on the settings lol 
> 
> 
> 
> I have 17 users on my Emby server currently, so does it check for suggestions across what all my users are watching? 
> 
> 
> 
> Thankfully I set up a local user account without auto approval so removing the 122 requests won't be a problem. When I first tried this without the Emby support I thought there was an option to choose which user on the media server you want to perform the suggestions on, unless I am misremembering. Will that be brought back? 

This feature has never been available, but I’ll implement it as soon as possible!

**Comment by giuseppe99barchetta** [comment]
Merged with 

https://github.com/giuseppe99barchetta/SuggestArr/issues/38
