### ISSUE TITLE
[REQ] Mutliple users

### ISSUE THREAD

**Issue by daerup** [giuseppe99barchetta/SuggestArr#38]
**Is your feature request related to a problem? Please describe.**
Currently SuggestArr  only works with one account. It would be nice if every user of a plex server could utilize SuggestArr  

**Describe the solution you'd like**
Allow users to enroll in SuggestArr and get content downloaded automatically. Maybe use the users account instead of a local user. Maybe also allow for the admin to change the amount of shows and movies per user instead of a global limit

**Describe alternatives you've considered**
Multiple instances, but seems rather tedious.

**Additional context**
Maybe make it more transparent how something was downloaded. Maybe add a tag inside radarr/sonarr that it was downloaded via SuggestArr. Also maybe instead of using an local user for requests, use the account of the account of a user to make the request, then use the api to automatically allow it, this would make it more transparent in Overseerr how something got in.

**Comment by giuseppe99barchetta** [comment]
I’ve confirmed that it’s already working! The Plex API returns the viewing history for all users, so SuggestArr will search for content recommendations based on the combined history of all users!
