### ISSUE TITLE
[BUG] Missing Keys

### ISSUE THREAD

**Issue by rubylaser** [giuseppe99barchetta/SuggestArr#39]
**Describe the bug**
I have this running via Docker connected to Plex and Overseerr. When view the logs, I get zero new requests and just see tons of errors like this. 
`2024-10-25 01:46:15,870 - ContentAutomation - WARNING - Error while processing item: Missing key for movie 'Monsters, Inc.'. Cannot process this item. Skipping` I see similar errors for all movies and shows. 

**To Reproduce**
1. Configure the app
2. Run
3. View the docker log

**Expected behavior**
Shouldn’t have tons of missing keys errors. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version latest

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS18
 - Browser Brave
 - Version latest

**Comment by giuseppe99barchetta** [comment]
Can you share your Plex library settings? Which agent are you using?

**Comment by rubylaser** [comment]
Sure! For movies, I'm using the Plex Movie agent and for TV Shows, I'm using the Plex Series agent. I'm on Plex Media Server version 1.41.2.9092.

**Comment by rubylaser** [comment]
Thanks for the speedy response! I've upgraded to the latest version of SuggestArr.  I was still met with the same errors.  So, I changed the agent on my movie library to TMDB, restarted SuggestArr, and forced a re-run.  I'm still seeing the same errors.
```
2024-10-25 14:03:14,955 - ContentAutomation - WARNING - Error while processing item: Missing key for movie 'The Fall Guy'. Cannot process this item. Skipping.
```

**Comment by giuseppe99barchetta** [comment]
> Thanks for the speedy response! I've upgraded to the latest version of SuggestArr. I was still met with the same errors. So, I changed the agent on my movie library to TMDB, restarted SuggestArr, and forced a re-run. I'm still seeing the same errors.
> 
> ```
> 2024-10-25 14:03:14,955 - ContentAutomation - WARNING - Error while processing item: Missing key for movie 'The Fall Guy'. Cannot process this item. Skipping.
> ```

Could you please run the following command and paste the output here? This will help me identify what’s causing the issue:

`curl -X GET "{YOUR_PLEX_URL}/status/sessions/history/all" -H "X-Plex-Token: {YOUR_PLEX_TOKEN}" -H "Accept: application/json"`

You can find your Plex token in the config_file.yaml or by following these steps:

1. Open your Plex application.
2. Navigate to the information panel for any movie.
3. Click on "Show XML" in the options.
4. Your Plex token will be at the end of the URL.

Thank you!

**Comment by giuseppe99barchetta** [comment]
> I did that and dumped the output to a json file. It's 31.5MB. Here is a link to it https://mega.nz/file/NUlnmIaK#1PW3I3Zf2MqY4wYs-iWXQ91hEg-iBGLemBnpCgQl2U8

Thank you! Please give me some time to check it, and I promise to return with a fix soon. :)

**Comment by giuseppe99barchetta** [comment]
> I did that and dumped the output to a json file. It's 31.5MB. Here is a link to it https://mega.nz/file/NUlnmIaK#1PW3I3Zf2MqY4wYs-iWXQ91hEg-iBGLemBnpCgQl2U8

Can you please try to rebuild with the nightly tag? I've just release an update that should fix your problem

**Comment by rubylaser** [comment]
That did it! Thank you :)
