### ISSUE TITLE
[REQ] use suggestarr without overseerr

### ISSUE THREAD

**Issue by NimdaBE** [giuseppe99barchetta/SuggestArr#43]
Hi,

Would it be possible to install and use suggestarr without something like overseerr? I would like to get suggestions based on my plex viewing history but i want to keep manual control over my downloads (where i get them, what quality, what subtitles,...) and what get’s adder to the arr-stack...

I’d rather get the suggestions from your app but add them to sonarr/radarr/wathever myself but the installation wizard won’t let me get past the overseerr api screen...

**Comment by giuseppe99barchetta** [comment]
> Hi,
> 
> Would it be possible to install and use suggestarr without something like overseerr? I would like to get suggestions based on my plex viewing history but i want to keep manual control over my downloads (where i get them, what quality, what subtitles,...) and what get’s adder to the arr-stack...
> 
> I’d rather get the suggestions from your app but add them to sonarr/radarr/wathever myself but the installation wizard won’t let me get past the overseerr api screen...

You can already have control over your download by creating a local Overseer user without auto-approval permission and approve it manually.

**Comment by giuseppe99barchetta** [comment]
> I’d rather get the suggestions from your app but add them to sonarr/radarr/wathever myself but the installation wizard won’t let me get past the overseerr api screen...

You should check the other open issue related to this error, rather than submitting it as part of a feature request.

**Comment by NimdaBE** [comment]
There is no error. I was inquiring if it was possible to use suggestarr’s suggestion mechanism based on plex without the use of overseerr altogether... The wizard won’t proceed without the overseerr api key. Installing overseerr and disabling all automatic functions then seems a waste of resources to me. If it’s not possible to use suggestarr without any overseerr installation then maybe it’s not the right recommendations tool for me...

**Comment by giuseppe99barchetta** [comment]
> There is no error. I was inquiring if it was possible to use suggestarr’s suggestion mechanism based on plex without the use of overseerr altogether... The wizard won’t proceed without the overseerr api key. Installing overseerr and disabling all automatic functions then seems a waste of resources to me. If it’s not possible to use suggestarr without any overseerr installation then maybe it’s not the right recommendations tool for me...

But why? You can configure Overseerr to avoid auto-downloading new content, as explained before. You can disable the automatic approval functions, allowing you to manually manage the suggested content. And you can approve the request like the screenshot

![image](https://github.com/user-attachments/assets/d9c3a50c-88ee-41bf-b2e0-676e93753e6a)

**Comment by NimdaBE** [comment]
Because i then have to download and install overseerr to get suggestarr installed and get suggestions from your platform. Getting recommendations from suggestarr and adding them myself directly in sonarr and radarr is all the functionaliteit i need...

**Comment by giuseppe99barchetta** [comment]
There's already a request feature opened for that
