### ISSUE TITLE
[BUG] Limitations not adhered to

### ISSUE THREAD

**Issue by rowanfuchs** [giuseppe99barchetta/SuggestArr#46]
I've set max 5 movies and 2 shows and a total of i assume 10 max content? but I received 200 new tv show downloads and 55 movie downloads.

**To Reproduce**
1. Configure the settings as in the screenshot.

**Expected behavior**
no more downloads per iterations than the settings

**Screenshots**
![image](https://github.com/user-attachments/assets/1bc7742c-b806-4178-8959-d9db7e338c82)

**Comment by giuseppe99barchetta** [comment]
> I've set max 5 movies and 2 shows and a total of i assume 10 max content? but I received 200 new tv show downloads and 55 movie downloads.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Configure the settings as in the screenshot.
> 
> **Expected behavior** no more downloads per iterations than the settings
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/48676736/380122121-1bc7742c-b806-4178-8959-d9db7e338c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI5NTMsIm5iZiI6MTcyOTg1MjY1MywicGF0aCI6Ii80ODY3NjczNi8zODAxMjIxMjEtMWJjNzc0MmMtYjgwNi00MTc4LTg5NTktZDlkYjdlMzM4YzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEwMzczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZWM3MzY0OTFhZjc5NTc2YTAzN2IxYzVlZDc0YWMwOTVmZTZjMTY2YTY4YWE4MjQ4MmFmMWI4NjlmMmUwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MrZMMB7K3vjBpqJrG21BS5EFkFyM_IAjBCKVR0RDPAg)

Yes, that's correct. The way it’s configured, for each piece of viewed content, SuggestArr will request up to 5 movies and 2 TV shows. So, for example, if your last 10 viewed items are all movies, it could request up to 5 similar movies for each one.

This applies to every user on your server as well.

**Comment by rowanfuchs** [comment]
I just realised that to, thank you for the clarification. it's a little to much as a default setting to start with for me. 

By the way, you might want to change the favicon from Vue.js to something fancy of your own 😀

**Comment by giuseppe99barchetta** [comment]
> I just realised that to, thank you for the clarification. it's a little to much as a default setting to start with for me.
> 
> By the way, you might want to change the favicon from Vue.js to something fancy of your own 😀

I'm currently working on implementing more granular filters. For now, you can set, for example, 2 movies and 1 TV show for each recently watched content.

As for the favicon, I know! 😅 But I haven’t had time to come up with a logo yet and sincerly I have completely no idea about it. I started just a week ago with SuggestArr.

**Comment by rowanfuchs** [comment]
Yeah, changing the `Max Content to fetch for each content` to one suffices for me, take it easy, everything in time.
