### ISSUE TITLE
[REQ] Any thoughts on bringing this to unRAID?

### ISSUE THREAD

**Issue by rh535** [giuseppe99barchetta/SuggestArr#58]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
If you could make a template for unRAID Community Applications

**Describe alternatives you've considered**
None

**Additional context**
None

Thanks for your work!

**Comment by giuseppe99barchetta** [comment]
Already working on this, in few days should be available :)

**Comment by giuseppe99barchetta** [comment]
> Awesome. Can't wait to use it!

You should able to install also using the docker compose provided in the readme in unraid
