### ISSUE TITLE
[BUG] 2024-10-26 01:31:27,963	ERROR	api_service.blueprints.automation.routes	Unexpected error: 

### ISSUE THREAD

**Issue by Arcau** [giuseppe99barchetta/SuggestArr#59]
Setup and configure - things authenticated fine. 
Got to ending page for summary. 
Attempt to Run Now
Times out with this error. 

2024-10-26 01:31:27,963	ERROR	api_service.blueprints.automation.routes	Unexpected error: 	
2024-10-26 01:30:31,018	ERROR	api_service.blueprints.automation.routes	Unexpected error: 	
2024-10-26 01:29:16,934	ERROR	api_service.blueprints.automation.routes	Unexpected error: 

No other logs showing or info for it.

**Comment by giuseppe99barchetta** [comment]
> Setup and configure - things authenticated fine. Got to ending page for summary. Attempt to Run Now Times out with this error.
> 
> 2024-10-26 01:31:27,963 ERROR api_service.blueprints.automation.routes Unexpected error: 2024-10-26 01:30:31,018 ERROR api_service.blueprints.automation.routes Unexpected error: 2024-10-26 01:29:16,934 ERROR api_service.blueprints.automation.routes Unexpected error:
> 
> No other logs showing or info for it.

Could you please provide more details about your configuration and the system you are using?

**Comment by Arcau** [comment]
using docker compose through portainer 
Service Emby
Jellyseer 

both authenticated fine 

API from TMDB authenticated from config setup 

![image](https://github.com/user-attachments/assets/1afbed16-d9a1-48dc-81ea-76c51ad815da)

Did have a thought - do I need to externally expose the suggestarr service for the tmdb api to work or?

**Comment by giuseppe99barchetta** [comment]
> using docker compose through portainer 
> 
> Service Emby
> 
> Jellyseer 
> 
> 
> 
> both authenticated fine 
> 
> 
> 
> API from TMDB authenticated from config setup 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/1afbed16-d9a1-48dc-81ea-76c51ad815da)
> 
> 
> 
> Did have a thought - do I need to externally expose the suggestarr service for the tmdb api to work or? 
> 
> 

Thank you for your patience. It’s not necessary to expose SuggestArr. I need to conduct some checks as I can’t reproduce the issue on my end. I’m hoping to push a fix for you as soon as possible.

**Comment by Woahai321** [comment]
Same exact issue: running all on Windows - Docker for the setup

**Comment by giuseppe99barchetta** [comment]
> Same exact issue: running all on Windows - Docker for the setup

Could you please try to run with the `nightly` tag?

**Comment by Woahai321** [comment]
> > Same exact issue: running all on Windows - Docker for the setup
> 
> Could you please try to run with the `nightly` tag?

I will have to try this in a few hours - heading out now, but will keep you posted!

**Comment by giuseppe99barchetta** [comment]
> using docker compose through portainer Service Emby Jellyseer
> 
> both authenticated fine
> 
> API from TMDB authenticated from config setup
> 
> ![image](https://private-user-images.githubusercontent.com/104758165/380376751-1afbed16-d9a1-48dc-81ea-76c51ad815da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTAxNzYsIm5iZiI6MTcyOTk0OTg3NiwicGF0aCI6Ii8xMDQ3NTgxNjUvMzgwMzc2NzUxLTFhZmJlZDE2LWQ5YTEtNDhkYy04MWVhLTc2YzUxYWQ4MTVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWM3MjllNmVlMGJkZDAxNGY0ZmIwOWI3MWE2NzRmYzc2ZjFiNTQ5ZDkzMTA0MGQxMzUzMzM5M2VkMDc4NGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-quAPlxQHS5V5deGECuhPO0sHBC2vnoGK7-8V52X-aA)
> 
> Did have a thought - do I need to externally expose the suggestarr service for the tmdb api to work or?

Could you please to try to update the docker image and re-test?

**Comment by Woahai321** [comment]
> > using docker compose through portainer Service Emby Jellyseer
> > both authenticated fine
> > API from TMDB authenticated from config setup
> > ![image](https://private-user-images.githubusercontent.com/104758165/380376751-1afbed16-d9a1-48dc-81ea-76c51ad815da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTAxNzYsIm5iZiI6MTcyOTk0OTg3NiwicGF0aCI6Ii8xMDQ3NTgxNjUvMzgwMzc2NzUxLTFhZmJlZDE2LWQ5YTEtNDhkYy04MWVhLTc2YzUxYWQ4MTVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMzM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWM3MjllNmVlMGJkZDAxNGY0ZmIwOWI3MWE2NzRmYzc2ZjFiNTQ5ZDkzMTA0MGQxMzUzMzM5M2VkMDc4NGE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-quAPlxQHS5V5deGECuhPO0sHBC2vnoGK7-8V52X-aA)
> > Did have a thought - do I need to externally expose the suggestarr service for the tmdb api to work or?
> 
> Could you please to try to update the docker image and re-test?

I mean, overall, the app appears to work. Which is good!

But, I get that blueprint error and some other api timeouts

api_service.blueprints.automation.routes	Unexpected error:

/api/v1/request timed out.

**Comment by Arcau** [comment]
I have pulled the nightly and still getting the error . 
2024-11-01 01:51:36,269	ERROR	api_service.blueprints.automation.routes	Unexpected error: 
I let it run for a while to see if allowing the timer to trigger it worked or not.

**Comment by Arcau** [comment]
2024-11-02 01:33:45,270 - api_service.blueprints.automation.routes - ERROR - Unexpected error:
Still erroring out - updated to the unraid app store docker and same thing on the system

**Comment by giuseppe99barchetta** [comment]
> 2024-11-02 01:33:45,270 - api_service.blueprints.automation.routes - ERROR - Unexpected error: Still erroring out - updated to the unraid app store docker and same thing on the system

I just released another update. Could you try updating and let me know if the issue persists? It might help to restart the container after updating to ensure all changes take effect. Thanks for helping troubleshoot this!

**Comment by Arcau** [comment]
Just updated the docker app and same thing, its working up until the point of trying to API. 

2024-11-05 11:41:31,269 - api_service.blueprints.automation.routes - ERROR - Unexpected error:
