### ISSUE TITLE
[BUG] Step 3/5 blank page after signing into Plex

### ISSUE THREAD

**Issue by Serenity23** [giuseppe99barchetta/SuggestArr#66]
**Describe the bug**
Step 3/5 shows a blank page. No options to select. 

**To Reproduce**
1. Click on Plex
2. Insert TMDB API
3. Will be prompted to log in to Plex to authenticate
4. Log in successful
5. Shows the belowscreenshot. 

**Expected behavior**
To show the appropriate page + fields re: step 3/5

**Screenshots**
![s](https://github.com/user-attachments/assets/17546a0e-8214-4a98-8a23-d10aa37c4242)
![logs](https://github.com/user-attachments/assets/c2da33c0-6125-4f97-949e-454f581ef1c6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 130.0.6723.70 

**Additional context**
Running this in a docker container on a synology NAS. Tried disabling firewall to see if it was a firewall issue; tried using incognito mode; tried using nightly image; tried Edge browser. 

Docker Compose:
services:
  suggestarr:
    image: ciuse99/suggestarr:nightly
    container_name: SuggestArr
    restart: always
    ports:
      - "8990:5000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume2/docker/suggestarr/app/config:/app/config/config_files

**Comment by giuseppe99barchetta** [comment]
Hi, thank you for the detailed bug reporting!

Have you tried to create a config.yaml file manually here?

`volume2/docker/suggestarr/app/config`

Let me know if it solves the issue, I need to check what's happening here.

**Comment by Serenity23** [comment]
I just added it, but the main issue still persists. It now can find the config.yaml, but I still get the blank on step 3/5. 

The log reads:
api_service.blueprints.config.routes | Error loading configuration: 'NoneType' object has no attribute 'get'

Also random - but when I click "copy" on the error log, it doesn't copy.

**Comment by giuseppe99barchetta** [comment]
Can you try with the nightly tag?

**Comment by Serenity23** [comment]
Yep. It worked initially - during my very first run (but it wasn’t
correctly detecting all my servers).

That’s when I logged out from my plex, and tried to log back in.

**Comment by Serenity23** [comment]
Oh to clarify - this was before I even had a config.yaml. This was my very first run. 

I would log out whenever I had to click “auth with Plex” - and then select “sign in as a different user”.

My config.yaml is blank.

**Comment by giuseppe99barchetta** [comment]
> Oh to clarify - this was before I even had a config.yaml. This was my very first run. After setting it up.
> 
> I would log out whenever I had to click “auth with Plex” - and then select “sign in as a different user”.
> 
> My config.yaml is blank.

That's strange. It’s normal for config.yaml to be empty initially, as it only gets saved in the final step. Could you try recreating the container and check if the issue persists?

**Comment by Serenity23** [comment]
I gave it another go - I wiped and re-setup from the start. And it set up fine. Thanks!
