### ISSUE TITLE
[BUG] I'm Blocked step 5, i can't click on save

### ISSUE THREAD

**Issue by OzZy02100** [giuseppe99barchetta/SuggestArr#67]
I'm Blocked step 5, i can't click on save.

By the way, I just installed the last version of Jellyfin.

**Comment by Xelator23** [comment]
I got the same on my first Try.
U can't save the config, use the normal compose and down't edit it or for Unraid use the app from the appstore.

**Comment by cup1dstunt** [comment]
Can confirm

![grafik](https://github.com/user-attachments/assets/79aaba2a-078f-40e4-b1ee-8362f0b1e3be)

**Comment by giuseppe99barchetta** [comment]
> Can confirm
> 
> ![grafik](https://private-user-images.githubusercontent.com/118675873/380662963-79aaba2a-078f-40e4-b1ee-8362f0b1e3be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDk3NzcsIm5iZiI6MTczMDEwOTQ3NywicGF0aCI6Ii8xMTg2NzU4NzMvMzgwNjYyOTYzLTc5YWFiYTJhLTA3OGYtNDBlNC1iMWVlLTgzNjJmMGIxZTNiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwOTU3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWVhMTZiMDk3MzhjYWMwY2EyZTIwN2YwMzQ3ODBkMzI0MjRkNGY1YTI5YjUyZmQwYWQwMzJiODRhODI0Y2ZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JKm6tWNKUcPJOiExxAZOZ5Mk9eHjMGa45wS_5X0GGt0)

Could you share your docker-compose? Also, could you check if there’s a config_file folder in the directory you specified in your docker-compose setup?

**Comment by cup1dstunt** [comment]
I use unraid community apps to look at new apps, I move over to docker-compose after a while if I like the apps and keep using them. There is no straightforward way to dissect the compose of Unraid community apps. So this might very well an issue with the template made by the person who put this in Unraid community apps. It worked flawlessly a couple of days ago (don't remember the version) but if you changed something in the compose commands, it's likely not updated in the template.

In the template, no data directory is defined, however, TMDB_api_key,jellyfin api url/jellyfin token, jellyseerr api url/jellyseerr token and some settings (namely: max_similar_movie, max_similar_tv, cron_times) are defined. 

Have you changed the volumes path of the compose or any of the variables mentioned above in the updates recently? That might be causing the issue

**Comment by giuseppe99barchetta** [comment]
> this is my template for Unraid
> 
> ```
> <?xml version="1.0"?>
> <Container version="2">
>   <Name>SuggestArr</Name>
>   <Repository>ciuse99/suggestarr:latest</Repository>
>   <Registry>https://hub.docker.com/r/ciuse99/suggestarr</Registry>
>   <Network>bridge</Network>
>   <MyIP/>
>   <Shell>bash</Shell>
>   <Privileged>false</Privileged>
>   <Support>https://github.com/giuseppe99barchetta/suggestarr/issues</Support>
>   <Project>https://github.com/giuseppe99barchetta/suggestarr</Project>
>   <Overview>Automatically request suggested movies and TV shows to Jellyseerr based on recently watched.</Overview>
>   <Category>Downloaders: MediaApp:Video</Category>
>   <WebUI>http://[IP]:[PORT:5000]</WebUI>
>   <TemplateURL>https://raw.githubusercontent.com/JamsRepos/Unraid-Templates/master/templates/suggestarr.xml</TemplateURL>
>   <Icon>https://github.com/giuseppe99barchetta/SuggestArr/blob/main/unraid/logo.png?raw=true</Icon>
>   <ExtraParams/>
>   <PostArgs/>
>   <CPUset/>
>   <DateInstalled>1730019804</DateInstalled>
>   <DonateText>Feeling generous?  Consider sponsoring me on GitHub!</DonateText>
>   <DonateLink>https://github.com/sponsors/JamsRepos</DonateLink>
>   <Requires/>
>   <Config Name="Web UI Port" Target="5000" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">5000</Config>
>   <Config Name="config" Target="/app/config/config_files" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/suggestarr</Config>
> </Container>
> ```

You should check if `/mnt/user/appdata/suggestarr` here the folder was created, if no there's some problem with unraid configuration.

**Comment by Xelator23** [comment]
> > this is my template for Unraid
> > ```
> > <?xml version="1.0"?>
> > <Container version="2">
> >   <Name>SuggestArr</Name>
> >   <Repository>ciuse99/suggestarr:latest</Repository>
> >   <Registry>https://hub.docker.com/r/ciuse99/suggestarr</Registry>
> >   <Network>bridge</Network>
> >   <MyIP/>
> >   <Shell>bash</Shell>
> >   <Privileged>false</Privileged>
> >   <Support>https://github.com/giuseppe99barchetta/suggestarr/issues</Support>
> >   <Project>https://github.com/giuseppe99barchetta/suggestarr</Project>
> >   <Overview>Automatically request suggested movies and TV shows to Jellyseerr based on recently watched.</Overview>
> >   <Category>Downloaders: MediaApp:Video</Category>
> >   <WebUI>http://[IP]:[PORT:5000]</WebUI>
> >   <TemplateURL>https://raw.githubusercontent.com/JamsRepos/Unraid-Templates/master/templates/suggestarr.xml</TemplateURL>
> >   <Icon>https://github.com/giuseppe99barchetta/SuggestArr/blob/main/unraid/logo.png?raw=true</Icon>
> >   <ExtraParams/>
> >   <PostArgs/>
> >   <CPUset/>
> >   <DateInstalled>1730019804</DateInstalled>
> >   <DonateText>Feeling generous?  Consider sponsoring me on GitHub!</DonateText>
> >   <DonateLink>https://github.com/sponsors/JamsRepos</DonateLink>
> >   <Requires/>
> >   <Config Name="Web UI Port" Target="5000" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">5000</Config>
> >   <Config Name="config" Target="/app/config/config_files" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/suggestarr</Config>
> > </Container>
> > ```
> 
> You should check if `/mnt/user/appdata/suggestarr` here the folder was created, if no there's some problem with unraid configuration.

i have no problems with this ... i forgot only to say this is working fine for me

**Comment by giuseppe99barchetta** [comment]
> > > this is my template for Unraid
> > > ```
> > > <?xml version="1.0"?>
> > > <Container version="2">
> > >   <Name>SuggestArr</Name>
> > >   <Repository>ciuse99/suggestarr:latest</Repository>
> > >   <Registry>https://hub.docker.com/r/ciuse99/suggestarr</Registry>
> > >   <Network>bridge</Network>
> > >   <MyIP/>
> > >   <Shell>bash</Shell>
> > >   <Privileged>false</Privileged>
> > >   <Support>https://github.com/giuseppe99barchetta/suggestarr/issues</Support>
> > >   <Project>https://github.com/giuseppe99barchetta/suggestarr</Project>
> > >   <Overview>Automatically request suggested movies and TV shows to Jellyseerr based on recently watched.</Overview>
> > >   <Category>Downloaders: MediaApp:Video</Category>
> > >   <WebUI>http://[IP]:[PORT:5000]</WebUI>
> > >   <TemplateURL>https://raw.githubusercontent.com/JamsRepos/Unraid-Templates/master/templates/suggestarr.xml</TemplateURL>
> > >   <Icon>https://github.com/giuseppe99barchetta/SuggestArr/blob/main/unraid/logo.png?raw=true</Icon>
> > >   <ExtraParams/>
> > >   <PostArgs/>
> > >   <CPUset/>
> > >   <DateInstalled>1730019804</DateInstalled>
> > >   <DonateText>Feeling generous?  Consider sponsoring me on GitHub!</DonateText>
> > >   <DonateLink>https://github.com/sponsors/JamsRepos</DonateLink>
> > >   <Requires/>
> > >   <Config Name="Web UI Port" Target="5000" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="true" Mask="false">5000</Config>
> > >   <Config Name="config" Target="/app/config/config_files" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/suggestarr</Config>
> > > </Container>
> > > ```
> > 
> > 
> > You should check if `/mnt/user/appdata/suggestarr` here the folder was created, if no there's some problem with unraid configuration.
> 
> i have no problems with this ... i forgot only to say this is working fine for me

Lol, thank you 😁
