### ISSUE TITLE
[REQ] Ability to monitor only the first season of TV

### ISSUE THREAD

**Issue by gbcatrinoiu** [giuseppe99barchetta/SuggestArr#71]
**Is your feature request related to a problem? Please describe.**
When a new TV show is added all seasons are monitored which will download everything before knowing if I will like it.

**Describe the solution you'd like**
Ability to select what to monitor:

- first episode
- first season
- last season

**Describe alternatives you've considered**
I think it could be done in overseer to monitor only some parts of the show when added, but everything will be partially added. I want everything monitored when adding manually in overseer, but partially monitored when added by suggestarr.

**Additional context**
-

**Comment by giuseppe99barchetta** [comment]
> **Is your feature request related to a problem? Please describe.** When a new TV show is added all seasons are monitored which will download everything before knowing if I will like it.
> 
> **Describe the solution you'd like** Ability to select what to monitor:
> 
> * first episode
> * first season
> * last season
> 
> **Describe alternatives you've considered** I think it could be done in overseer to monitor only some parts of the show when added, but everything will be partially added. I want everything monitored when adding manually in overseer, but partially monitored when added by suggestarr.
> 
> ## **Additional context**

Hi! Thank you so much for the suggestion. I've looked into it, and while I couldn’t find a way to request just a single episode via Overseer, I’ve added a feature to control the number of seasons requested. You’ll now see a new input field where you can specify the number of seasons to monitor:

- Leaving it blank will request all available seasons.
- Entering "1" will monitor only the first season.
- Entering "3" will monitor the first three seasons.

This should give more flexibility over how much content is initially requested. What do you think? If you’re available, I’d really appreciate your help testing this on the `nightly` tag!

Thanks again for your support!

**Comment by gbcatrinoiu** [comment]
Hi! I tested it and it works well, adding only the first or the first couple of seasons. On second thought selecting only the first episode might even be too much, so it is perfect. Great work and thanks for implementing it!

**Comment by gbcatrinoiu** [comment]
Not related to this feature req but I noticed that if one movie/tv show is already requested in overseer by another user and requestarr adds it as well, it is then marked as added by requestarr user.

Doesn't make more sense to keep the original user as the requester?

**Comment by giuseppe99barchetta** [comment]
> > Leaving it blank will request all available seasons.
> 
> > Entering` "1" will monitor only the first season.
> 
> > Entering "3" will monitor the first three seasons.
> 
> > This should give more flexibility over how much content is initially requested. What do you think? If you’re available, I’d really appreciate your help testing this on the nightly tag!
> 
> 
> Sorry to jump in into a closed issue, but I'm curious. How does this work if the user watches the first few episodes or the first season of that show? Will SuggestArr add the next season in line? If this isn't done yet, could this be possible to add? Potentially even monitor the next seasons/releases that aren't up yet if the show was interesting enough for someone to watch the whole thing through?


Hi, thanks for your question! Currently, SuggestArr doesn’t automatically add the next season after a user watches the season, but it’s a great idea. Tracking watched progress or monitoring upcoming seasons could be valuable features. Could you open a new issue for this? It’ll help track the discussion and any future development.
