### ISSUE TITLE
[BUG] Duplicate Requests

### ISSUE THREAD

**Issue by vahtos** [giuseppe99barchetta/SuggestArr#74]
SuggestArr is making duplicate requests/not considering previous requests. Here is an example:

![image](https://github.com/user-attachments/assets/991dee51-5108-4b4a-bb6a-1391f6f62e63)

**Comment by giuseppe99barchetta** [comment]
Hey @vahtos! I've just pushed a fix for this issue in `nightly` tag. Let me know if it resolves the issue on your end. 

Thanks again for helping test it out!

**Comment by vahtos** [comment]
Yes, this has stopped happening now using the current nightly build.

**Comment by giuseppe99barchetta** [comment]
> Yes, this has stopped happening now using the current nightly build.

Thank you so much for all your help with this project! Your contributions have become an essential part of its development!

**Comment by vahtos** [comment]
No problem, this app is so useful! Happy to help.

It looks like I said it works a bit too soon. I _think_ it started making duplicate requests when I changed the config. I did a complete reset of the configuration and got this to happen:
![image](https://github.com/user-attachments/assets/2d672634-f6ec-47ee-bdba-de5ca70b45c1)

**Comment by giuseppe99barchetta** [comment]
Thank you again! It's strange that the duplicate requests are still occurring. I’ll need a bit more time to investigate and work on a fix for this issue.

**Comment by vahtos** [comment]
I checked the logs and there is an issue with getting the requests that have already been made:

```
2024-10-30 17:01:10,723 - SeerClient - INFO - Fetched 0 total requests from Jellyseer.
```

**Comment by giuseppe99barchetta** [comment]
> I checked the logs and there is an issue with getting the requests that have already been made:
> 
> ```
> 2024-10-30 17:01:10,723 - SeerClient - INFO - Fetched 0 total requests from Jellyseer.
> ```
> 
> I think I know what is going on here... after I ran into #76, I started removing the API key from the configuration each time to ensure that doesn't happen again. I thought this wasn't causing any issues, but it quietly breaks pulling existing requests (the logic for that does not use the local account) and causes this issue.
> 
> I just tested and confirmed that putting the API Key back fixes this issue and previous requests are considered. Sorry!

Thank you for the update! Just to clarify, with the API key added back, do you still see any instances of the double requests issue, or has that resolved it entirely?

**Comment by vahtos** [comment]
That has solved it completely.
