### ISSUE TITLE
[BUG] Requests Made as Wrong User

### ISSUE THREAD

**Issue by vahtos** [giuseppe99barchetta/SuggestArr#76]
SuggestArr currently requires users to add an API key for Overseerr (I have not tested on Jellyseerr, I don't use it) in order to provide a username/password for a local account. This should not be required, and can be circumvented without problems by clearing the API key after entering the local username/password. I have also had it request as the admin user (which with my setup auto-approved the requests) via the CRON job when the API key is left in the configuration.

Suggested changes:
1. Allow users to enter a local account without requiring an API key for Overseerr (and Jellyseerr, assuming it works the same way)
2. Review CRON process to ensure it uses the local account when a user provides both an API key and a local account. I'm unsure if this happens _every_ time, or if something in the code is assumed to be ordered, but is not necessarily.

**Comment by vahtos** [comment]
I'm trying to investigate this/reproduce it, but I am finding that with the currently nightly build, the CRON job does not seem to work at all. I set the CRON configuration in the UI to `*/1 * * * *` so that it will run every minute and watched the logs and nothing happens.

I think this is because the route changed from `/run_now` to `/force_run`. The CRON command did not get updated in `update_cron_job()` and still is:
```python
cron_command = "curl -X POST http://localhost:5000/run_now >> /var/log/cron.log 2>&1"
```

**Comment by giuseppe99barchetta** [comment]
Hi @vahtos, thank you againg for looking into this and spotting the issue!

Yes, the /force_run endpoint update should indeed be reflected in the cron command. This has been corrected in the latest nightly tag, so you should be able to set the cron schedule in the UI without issues now.

Let me know if the cron job runs as expected after pulling the latest nightly, and thank you again for helping to catch this!

**Comment by vahtos** [comment]
No problem! I can confirm that the CRON task is fixed now. I am still unable to reproduce the issue.

I looked through the code and didn't see anything that stuck out to me. I also tried changing the session token to be an invalid value (this issue originally happened after Suggestarr had been sitting for some time, so I thought maybe the token being used was invalidated and that caused the issue). Suggestarr handled that just fine, requesting a new token. Though, it does not update the config file with the new token -- though this is not functionally a problem, since it re-authenticates whenever there is _some_ token value and the request fails.

The only thing I can think of (assuming this is still an issue) would be that my method of testing is flawed, and when using a stale token Overseerr doesn't respond with a code 404 or 404, but instead uses a 401 Unauthorized. That would change the code path here:
https://github.com/giuseppe99barchetta/SuggestArr/blob/689b21bdc06f6b0ffb04d60d66eb847bc9f03ce7/api_service/services/jellyseer/seer_client.py#L117-L124

I'm not that familiar with the code base, but could that cause it to fall back to using the API key instead of the local account?

**Comment by giuseppe99barchetta** [comment]
> I'm not that familiar with the code base, but could that cause it to fall back to using the API key instead of the local account?

Theoretically, no; if `use_cookie` is set to `true`, it shouldn't request content as **Admin**. This is because `use_cookie `is only `true `if a **username and password for Overseer/Jellyseer are provided**. 

I’ve had difficulty reproducing this issue, so I’ll need to investigate further to understand what’s happening here.

**Comment by vahtos** [comment]
I don't want to waste your time on this. I'll keep an eye on it and if it happens again I will refile a ticket with logs. It only happened once and I have been unable to reproduce it since.
