### ISSUE TITLE
[REQ] Log Prior Requests and Do Not Request Again

### ISSUE THREAD

**Issue by sameleff** [giuseppe99barchetta/SuggestArr#80]
**Is your feature request related to a problem? Please describe.**
Currently, SuggestArr runs based on a cronjob. At each execution, it selects and automatically requests content in Overseerr/Jellyseerr. After reviewing, if the user declines certain requests, they are re-requested at the next execution of SuggestArr.

**Describe the solution you'd like**
Upon each execution, log each item that is requested. Only submit a new request for items that do not already exist in the library and have not already been requested in the past.

**Describe alternatives you've considered**
Open to alternatives, I'm sure there is a more elegant solution than creating a database file.

**Additional context**
N/A

**Comment by vahtos** [comment]
Could you confirm something about your setup? I'm assuming you're using an unprivileged local account for SuggestArr since this is about declined requests. When you setup SuggestArr, after entering this accounts login information, did you clear out the API key for the admin user?

If you do this, then SuggestArr will fail to pull previous requests and so will make duplicates. See https://github.com/giuseppe99barchetta/SuggestArr/issues/74#issuecomment-2447818131

**Comment by sameleff** [comment]
You are correct (I am using a local Overseerr user)...I left the API included after adding the user during initial setup. It does seem like refreshing the config helped...to test, I edited the config and removed the API key, then ran SuggestArr (it requested duplicates, even within that same run). Then I edited the config again, this time putting the API key back. When I ran SuggestArr next, it did not request anything.

**Comment by sameleff** [comment]
It appears I closed this prematurely...
When I updated to the `nightly` release, SuggestArr re-requested a movie that had already been previously requested (and the request denied). It was able to correctly prevent duplicate requests for other TV Shows / Movies during the same run.

**Comment by giuseppe99barchetta** [comment]
> It appears I closed this prematurely... When I updated to the `nightly` release, SuggestArr re-requested a movie that had already been previously requested (and the request denied). It was able to correctly prevent duplicate requests for other TV Shows / Movies during the same run.

When you decline a request on Overseer you also delete it?

**Comment by sameleff** [comment]
No, I just decline them. Also, SuggestArr has requested the same item twice during the same run.
1. I have no open requests
2. After running SuggestArr, the same item is requested twice
This doesn't happen to every item SuggestArr requests during a run, so it's in a better state than earlier, but still not completely resolved.

**Comment by Chuacheee** [comment]
I have the same error here
