### ISSUE TITLE
[REQ] Filter Viewing History by User

### ISSUE THREAD

**Issue by sameleff** [giuseppe99barchetta/SuggestArr#81]
**Is your feature request related to a problem? Please describe.**
Currently, SuggestArr pulls viewing history for all users on the linked media server. This tool is more useful when executed on a user-by-user basis.

**Describe the solution you'd like**
During the configuration process, provide the ability to filter the scope of the sampled viewing history by media server user. Only provide recommendations based on the selected user(s) viewing history.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by giuseppe99barchetta** [comment]
Hi @sameleff, I’ve just published the update in the `nightly` tag, and I’d really appreciate your feedback to ensure everything is functioning as expected!

**Comment by sameleff** [comment]
Cool! It does seem to be filtering requests now on a particular user. Strangely, when it displays of users to include, a few of them (not all) are duplicated and show up twice. When I click a box for a particular user, the program selects the duplicated box as well. Looks like there is a bug in the method to display the list of users, but the functionality appeared to work.
