### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sldless** [giuseppe99barchetta/SuggestArr#87]
**Describe the bug**
Failed to validate Jellyfin Key or retrieve libraries. (have no end slashes just the domain | Ex. https://domain.com )

- API Key works based on curl. 

- Using example compose.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by giuseppe99barchetta** [comment]
Could you please provide more details about your setup? Specifically, which Docker version you're using, the platform (e.g., Portainer, CasaOS, UnRaid), and the versions of Jellyfin and SuggestArr.

Thank you!

**Comment by sldless** [comment]
Jellyfin 10.10.0 | SuggestArr nightly | Debian 12On Nov 6, 2024, at 3:24 AM, Giuseppe Barchetta ***@***.***> wrote:﻿
Could you please provide more details about your setup? Specifically, which Docker version you're using, the platform (e.g., Portainer, CasaOS, UnRaid), and the versions of Jellyfin and SuggestArr.
Thank you!

**Comment by sldless** [comment]
Looks like it's failing to request `https://domain.com/Library/VirtualFolders`. The problem is I can access it from the open web and can even curl it through the container

**Comment by giuseppe99barchetta** [comment]
> My bad, Version is: Docker version 27.3.1, build ce12230. And the `latest` tag doesn't work | Using traefik | Logs say 403

If you have Jellyfin on the same network as SuggestArr could you please try with local address? It's strange that doesn't work, also on my SuggestArr instance I use a domain name for Jellyfin

**Comment by sldless** [comment]
Local address works, would you know any reason why external doesn't?

**Comment by giuseppe99barchetta** [comment]
> Local address works, would you know any reason why external doesn't?

Your domain is under SSL?

**Comment by sldless** [comment]
> > Local address works, would you know any reason why external doesn't?
> 
> Your domain is under SSL?

Yes
