### ISSUE TITLE
[REQ] Allow Ability To Change Port

### ISSUE THREAD

**Issue by thorman123** [giuseppe99barchetta/SuggestArr#97]
**Is your feature request related to a problem? Please describe.**

Trying to install via docker on a synology NAS doesn't deploy using port 5000. When changing the port before deploying I can't access the webui at all.

**Describe the solution you'd like**

Either allow changing of the port before deploying or have a config file to change after deployment.

**Comment by jbolla** [comment]
I see this is marked as completed, but I can't find anything in the docs about how to do this, and a brief look through the code didn't show anything obvious.
